======================================================================
FAIL: test_version (test_version.TestVersion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\pyenbc\_unittests\ut_module\test_version.py", line 42, in test_version
    assert f[0] == __version__
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
